language: rust
matrix:
  fast_finish: false
  include:
  - rust: stable
  - rust: nightly
  allow_failures:
  - rust: nightly

script:
  - cargo build --all --release --verbose
  - cargo test --all --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --no-default-features; fi
