[package]
name = "wasm-utils"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
parity-wasm = "0.27"
log = "0.3"
env_logger = "0.4"
lazy_static = "0.2"
clap = "2.24"
glob = "0.2"
byteorder = "1"

[dev-dependencies]
tempdir = "0.3"
wabt = "0.2"

[lib]

[[bin]]
name = "wasm-prune"
path = "prune/src/main.rs"

[[bin]]
name = "wasm-ext"
path = "ext/src/main.rs"

[[bin]]
name = "wasm-gas"
path = "gas/src/main.rs"

[[bin]]
name = "wasm-build"
path = "build/src/main.rs"
